# Generated by Django 6.0.6 on 2026-07-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
    ]
